### PR TITLE
Some stuff

### PR DESCRIPTION
**Pull request by lutz**
- includes new localization system
- some code cleanups
- (hopefully) completely german support
- integrate `FormBase` class to to support some windows  forms ui events

### CODE REVIEW

**Comment by Belim** [comment]
DriveSelectionHandler is currently broken. BtnOK is without function

**Comment by lutz** [comment]
@Belim. What do you mean? The drive selection form should works correctly. The btnOk button is set as Accept button of the form and the btnExit button as Cancel button. If the user use it so DialogResult Property of Form ahould autoset through Ok or Cancel. So you dont need an click handler and so on.

**Comment by Belim** [comment]
@lutz Yes, I mean the Drivehandler and I have received numerous feedback that nothing happens when you press the Ok, Cancel button. I checked it quickly yesterday and I can confirm it. I can take a look at it by the night, if not before.

**Comment by lutz** [comment]
@Belim With the next pull request it should be worked again. I forgot to set the `DialogResult `Property of the Buttons and Call `.ShowDialog` for the Forms

**Pull request merged**
